name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps
        run: sudo apt install libcmocka-dev

      - name: Test script
        run: make test
